# MCMC simulation settings
file_base: "data/Q0000"
snapnum: 0
output_base: "output/Q0/HIGHZ_NGC_Q0_1000_k03"

# Model parameters
v_th: 513.68
delta_v: 110.8
ns_type: 0

n_mc: 1000
kmax: 0.30

step_covariance:
- [62.39, 132.88]
- [132.88, 285.86]
