# MCMC simulation settings
file_base: "data/Q0000"
snapnum: 2
#output_base: "output/Q0/LOWZ_NGC_Q0_500"
output_base: "output/Q0/LOWZ_NGC_Q0_1000_6"

# Model parameters
v_th: 567.7
delta_v: 126.8
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [82.29, 209.20]
  - [209.20, 533.63]
