# MCMC simulation settings
file_base: "data/Q0000"
snapnum: 2
#output_base: "output/Q0/LOWZ_SGC_Q0_500"
output_base: "output/Q0/LOWZ_SGC_Q0_1000"

# Model parameters
v_th: 480
delta_v: 90.8
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [484.39, 605.53]
  - [605.53, 807.76]
