# MCMC simulation settings
file_base: "data/Q0010"
snapnum: 0
#output_base: "output/Q10/HIGHZ_SGC_Q10_500"
output_base: "output/Q10/HIGHZ_SGC_Q10_1000_1"

# Model parameters
v_th: 600
delta_v: 140
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [1467.33, 3216.04]
  - [185.39, 7147.18]
