# MCMC simulation settings
file_base: "data/Q0010"
snapnum: 2
#output_base: "output/Q10/LOWZ_SGC_Q10_500"
output_base: "output/Q10/LOWZ_SGC_Q10_1000"

# Model parameters
v_th: 771.9
delta_v: 185.6
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [63.55, 185.39]
  - [185.39, 552.71]
