# MCMC simulation settings
file_base: "data/Q0011"
snapnum: 0
#output_base: "output/Q11/HIGHZ_SGC_Q11_500"
output_base: "output/Q11/HIGHZ_SGC_Q11_1000_1"

# Model parameters
v_th: 428.1
delta_v: 52.2
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [1067.01, 629.01]
  - [629.01, 417.94]
