# MCMC simulation settings
file_base: "data/Q0011"
snapnum: 0
#output_base: "output/Q11/HIGHZ_NGC_Q11_500"
output_base: "output/Q11/HIGHZ_NGC_Q11_1000_4"

# Model parameters
#v_th: 467.4
#delta_v: 89.4

v_th: 399
delta_v: 4.9
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [75.39, 129.35]
#  - [129.35, 225.81]

#step_covariance:
#  - [118.39, 140.74]
#  - [140.74, 173.54]

#step_covariance:
#  - [247.78, 263.62]
#  - [263.62, 293.02]

step_covariance:
  - [961.47, 738.03]
  - [738.03, 614.53]
