# MCMC simulation settings
file_base: "data/Q0011"
snapnum: 2
#output_base: "output/Q11/LOWZ_NGC_Q11_500"
output_base: "output/Q11/LOWZ_NGC_Q11_1000_2"

# Model parameters
v_th: 474.2
delta_v: 81.6
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [16.29, 21.11]
  - [21.11, 33.28]
