# MCMC simulation settings
file_base: "data/Q0012"
snapnum: 2
#output_base: "output/Q12/LOWZ_NGC_Q12_500"
output_base: "output/Q12/LOWZ_NGC_Q12_1000_2"

# Model parameters
v_th: 600
delta_v: 130

ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [334.82, 812.35]
  - [812.35, 1975.85]
