# MCMC simulation settings
file_base: "data/Q0012"
snapnum: 0
#output_base: "output/Q12/HIGHZ_SGC_Q12_500"
output_base: "output/Q12/HIGHZ_SGC_Q12_1000_1"

# Model parameters

v_th: 406.3
delta_v: 40.2

ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [417.42, 573.12]
  - [573.12, 821.48]
