# MCMC simulation settings
file_base: "data/Q0013"
snapnum: 2
#output_base: "output/Q13/LOWZ_NGC_Q13_500"
output_base: "output/Q13/LOWZ_NGC_Q13_1000_2"

# Model parameters
v_th: 701.5
delta_v: 170
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [72.92, 231.55]
  - [231.55, 747.14]
