# MCMC simulation settings
file_base: "data/Q0013"
snapnum: 0
#output_base: "output/Q13/HIGHZ_SGC_Q13_500"
output_base: "output/Q13/HIGHZ_SGC_Q13_1000_1"

# Model parameters
v_th: 480
delta_v: 90
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [278.80, 661.27]
  - [661.27, 1591.98]
