# MCMC simulation settings
file_base: "data/Q0013"
snapnum: 0
#output_base: "output/Q13/HIGHZ_NGC_Q13_500"
output_base: "output/Q13/HIGHZ_NGC_Q13_1000_1"

# Model parameters
v_th: 603.7
delta_v: 146.7
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [94.37, 244.45]
#  - [244.45, 639.50]

#step_covariance:
#  - [19.57, 54.70]
#  - [54.70, 155.50]

step_covariance:
  - [14.99, 43.35]
  - [43.35, 127.66]
