# MCMC simulation settings
file_base: "data/Q0014"
snapnum: 2
#output_base: "output/Q14/LOWZ_SGC_Q14_500"
output_base: "output/Q14/LOWZ_SGC_Q14_1000"

# Model parameters
v_th: 507.2
delta_v: 96.2
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [124.38, 200.56]
  - [200.56, 329.09]
