# MCMC simulation settings
file_base: "data/Q0014"
snapnum: 2
#output_base: "output/Q14/LOWZ_NGC_Q14_500"
output_base: "output/Q14/LOWZ_NGC_Q14_1000_1"

# Model parameters
v_th: 534.9
delta_v: 105
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [6.576, 12.922]
  - [12.922, 27.410]
