# MCMC simulation settings
file_base: "data/Q0015"
snapnum: 0
#output_base: "output/Q15/HIGHZ_NGC_Q15_500"
output_base: "output/Q15/HIGHZ_NGC_Q15_1000_2"

# Model parameters
v_th: 402
delta_v: 31.95
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [194.52, 369.39]
#  - [369.39, 705.81]

#step_covariance:
#  - [176.05, 248.93]
#  - [248.93, 364.09]

step_covariance:
  - [213.42, 250.56]
  - [250.56, 306.37]
