# MCMC simulation settings
file_base: "data/Q0015"
snapnum: 2
#output_base: "output/Q15/LOWZ_SGC_Q15_500"
output_base: "output/Q15/LOWZ_SGC_Q15_1000"

# Model parameters
v_th: 491.6
delta_v: 94.5
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [213.42, 250.56]
  - [250.56, 306.37]
