# MCMC simulation settings
file_base: "data/Q0015"
snapnum: 2
#output_base: "output/Q15/LOWZ_NGC_Q15_500"
output_base: "output/Q15/LOWZ_NGC_Q15_1000_1"

# Model parameters
v_th: 475.4
delta_v: 81
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [10.038, 16.481]
  - [16.481, 28.535]
