# MCMC simulation settings
file_base: "data/Q0016"
snapnum: 0
#output_base: "output/Q16/HIGHZ_NGC_Q16_500"
output_base: "output/Q16/HIGHZ_NGC_Q16_1000_1"

# Model parameters
v_th: 430.2
delta_v: 68.76
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [156.745, 284.946]
#  - [284.946, 522.915]

step_covariance:
  - [321.54, 585.884]
  - [585.884, 1091.358]
