# MCMC simulation settings
file_base: "data/Q0016"
snapnum: 0
#output_base: "output/Q16/HIGHZ_SGC_Q16_500"
output_base: "output/Q16/HIGHZ_SGC_Q16_1000_1"

# Model parameters
v_th: 378
delta_v: 23.8
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [450.78, 569.61]
  - [569.61, 751.37]
