# MCMC simulation settings
file_base: "data/Q0016"
snapnum: 2
#output_base: "output/Q16/LOWZ_NGC_Q16_500"
output_base: "output/Q16/LOWZ_NGC_Q16_1000_2"

# Model parameters
v_th: 520
delta_v: 109
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [134.84, 334.54]
  - [334.54, 838.27]
