# MCMC simulation settings
file_base: "data/Q0016"
snapnum: 2
#output_base: "output/Q16/LOWZ_SGC_Q16_500"
output_base: "output/Q16/LOWZ_SGC_Q16_1000"

# Model parameters
v_th: 491.5
delta_v: 97
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [321.54, 585.88]
  - [585.88, 1091.36]
