# MCMC simulation settings
file_base: "data/Q0017"
snapnum: 0
#output_base: "output/Q17/HIGHZ_NGC_Q17_500"
output_base: "output/Q17/HIGHZ_NGC_Q17_1000_1"

# Model parameters
v_th: 615.4
delta_v: 148.9
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]
#step_covariance:
#  - [130.54, 316.79]
#  - [316.79, 772.41]

step_covariance:
  - [93.83, 226.78]
  - [226.78, 550.31]
