# MCMC simulation settings
file_base: "data/Q0017"
snapnum: 0
#output_base: "output/Q17/HIGHZ_SGC_Q17_500"
output_base: "output/Q17/HIGHZ_SGC_Q17_1000_1"

# Model parameters
v_th: 424.4
delta_v: 56.2
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [731.37, 1360.30]
  - [1360.30, 2569.10]
