# MCMC simulation settings
file_base: "data/Q0017"
snapnum: 2
#output_base: "output/Q17/LOWZ_NGC_Q17_500"
output_base: "output/Q17/LOWZ_NGC_Q17_1000_1"

# Model parameters
v_th: 587.1
delta_v: 123.7
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [15.308, 34.962]
  - [34.962, 81.893]
