# MCMC simulation settings
file_base: "data/Q0017"
snapnum: 2
#output_base: "output/Q17/LOWZ_SGC_Q17_500"
output_base: "output/Q17/LOWZ_SGC_Q17_1000"

# Model parameters
v_th: 581
delta_v: 125.6
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [93.83, 226.78]
  - [226.78, 550.31]
