# MCMC simulation settings
file_base: "data/Q0018"
snapnum: 2
#output_base: "output/Q18/LOWZ_SGC_Q18_500"
output_base: "output/Q18/LOWZ_SGC_Q18_1000"

# Model parameters
v_th: 476.9
delta_v: 83.5
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [102.35, 116.39]
  - [116.39, 138.35]
