# MCMC simulation settings
file_base: "data/Q0018"
snapnum: 0
#output_base: "output/Q18/HIGHZ_SGC_Q18_500"
output_base: "output/Q18/HIGHZ_SGC_Q18_1000_1"

# Model parameters
v_th: 405
delta_v: 40
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [562.32, 691.46]
  - [691.46, 890.62]
