# MCMC simulation settings
file_base: "data/Q0018"
snapnum: 2
#output_base: "output/Q18/LOWZ_NGC_Q18_500"
output_base: "output/Q18/LOWZ_NGC_Q18_1000_1"

# Model parameters
v_th: 491.1
delta_v: 83.6
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [18.14, 26.45]
  - [26.45, 40.25]
