# MCMC simulation settings
file_base: "data/Q0018"
snapnum: 0
#output_base: "output/Q18/HIGHZ_NGC_Q18_500"
output_base: "output/Q18/HIGHZ_NGC_Q18_1000_2"

# Model parameters
v_th: 410
delta_v: 40
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [54.56, 91.80]
#  - [91.80, 159.12]

#step_covariance:
#  - [33.42, 47.21]
#  - [47.21, 69.25]

step_covariance:
  - [102.35, 116.39]
  - [116.39, 138.35]
