# MCMC simulation settings
file_base: "data/Q0019"
snapnum: 0
#output_base: "output/Q19/HIGHZ_SGC_Q19_500"
output_base: "output/Q19/HIGHZ_SGC_Q19_1000_1"

# Model parameters
v_th: 543.5
delta_v: 124.3
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [1018.85, 1420.91]
  - [1420.91, 2028.80]
