# MCMC simulation settings
file_base: "data/Q0019"
snapnum: 0
#output_base: "output/Q19/HIGHZ_NGC_Q19_500"
output_base: "output/Q19/HIGHZ_NGC_Q19_1000_1"

# Model parameters
v_th: 563
delta_v: 125.6
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [171.26, 366.55]
#  - [366.55, 788.19]

step_covariance:
  - [221.26, 465.98]
  - [465.98, 987.49]
