# MCMC simulation settings
file_base: "data/Q0019"
snapnum: 2
#output_base: "output/Q19/LOWZ_SGC_Q19_500"
output_base: "output/Q19/LOWZ_SGC_Q19_1000"

# Model parameters
v_th: 541.8
delta_v: 100.6
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [221.26, 465.98]
  - [465.98, 987.49]
