# MCMC simulation settings
file_base: "data/Q0019"
snapnum: 2
#output_base: "output/Q19/LOWZ_NGC_Q19_500"
output_base: "output/Q19/LOWZ_NGC_Q19_1000_1"

# Model parameters
v_th: 522
delta_v: 83
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [192.70, 296.60]
  - [296.60, 460.68]
