# MCMC simulation settings
file_base: "data/Q0001"
snapnum: 0
output_base: "output/Q1/HIGHZ_NGC_Q1_1000_k03_1"

# Model parameters
v_th: 667
delta_v: 165
ns_type: 0

n_mc: 1000
kmax: 0.3

step_covariance:
  - [38.621, 117.17]
  - [117.17, 370.65]

mcmc_seed: 1
