# MCMC simulation settings
file_base: "data/Q0001"
snapnum: 0
output_base: "output/Q1/HIGHZ_NGC_Q1_1000_k03_1"

# Model parameters
v_th: 712.9
delta_v: 180.2
ns_type: 0

n_mc: 1000
kmax: 0.3

step_covariance:
  - [292.81744, 899.59014]
  - [899.59014, 2776.3055]

mcmc_seed: 1
