# MCMC simulation settings
file_base: "data/Q0001"
snapnum: 0
#output_base: "output/Q1/HIGHZ_SGC_Q1_500"
output_base: "output/Q1/HIGHZ_SGC_Q1_1000_1"

# Model parameters
v_th: 434.4
delta_v: 53.9
ns_type: 1

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [484.39, 605.53]
#  - [605.53, 807.76]

#step_covariance:
#  - [521.39, 552.27]
#  - [552.27, 677.52]

step_covariance:
  - [580.36, 621.59]
  - [621.59, 753.94]
