# MCMC simulation settings
file_base: "data/Q0001"
snapnum: 2
#output_base: "output/Q1/LOWZ_NGC_Q1_500"
output_base: "output/Q1/LOWZ_NGC_Q1_1000_2"

# Model parameters
v_th: 600
delta_v: 135
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [343.82, 646.67]
  - [646.67, 1216.44]
