# MCMC simulation settings
file_base: "data/Q0001"
snapnum: 2
#output_base: "output/Q1/LOWZ_SGC_Q1_500"
output_base: "output/Q1/LOWZ_SGC_Q1_1000"

# Model parameters
v_th: 506.3
delta_v: 90
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [580.36, 621.59]
  - [621.59, 753.94]
