# MCMC simulation settings
file_base: "data/Q0020"
snapnum: 0
#output_base: "output/Q20/HIGHZ_SGC_Q20_500"
output_base: "output/Q20/HIGHZ_SGC_Q20_1000_1"

# Model parameters
v_th: 601.1
delta_v: 151.8
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [374.80, 770.58]
  - [770.58, 1604.86]
