# MCMC simulation settings
file_base: "data/Q0020"
snapnum: 2
#output_base: "output/Q20/LOWZ_NGC_Q20_500"
output_base: "output/Q20/LOWZ_NGC_Q20_1000_3"

# Model parameters
v_th: 723.8
delta_v: 174.3
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [1.72, 3.81]
  - [3.81, 10.16]
