# MCMC simulation settings
file_base: "data/Q0020"
snapnum: 0
#output_base: "output/Q20/HIGHZ_NGC_Q20_500"
output_base: "output/Q20/HIGHZ_NGC_Q20_1000_2"

# Model parameters
v_th: 622.3
delta_v: 152.1
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [25.63, 75.41]
  - [75.41, 225.01]
