# MCMC simulation settings
file_base: "data/Q0021"
snapnum: 0
#output_base: "output/Q21/HIGHZ_SGC_Q21_500"
output_base: "output/Q21/HIGHZ_SGC_Q21_1000_1"

# Model parameters
v_th: 385
delta_v: 30
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [1367.10, 835.18]
  - [835.18, 568.17]
