# MCMC simulation settings
file_base: "data/Q0021"
snapnum: 2
#output_base: "output/Q21/LOWZ_SGC_Q21_500"
output_base: "output/Q21/LOWZ_SGC_Q21_1000"

# Model parameters
v_th: 466.6
delta_v: 91.2
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [160.76, 250.45]
  - [250.45, 397.72]
