# MCMC simulation settings
file_base: "data/Q0021"
snapnum: 2
#output_base: "output/Q21/LOWZ_NGC_Q21_500"
output_base: "output/Q21/LOWZ_NGC_Q21_1000_1"

# Model parameters
v_th: 470
delta_v: 89
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [17.34, 36.03]
  - [36.03, 77.68]
