# MCMC simulation settings
file_base: "data/Q0022"
snapnum: 0
#output_base: "output/Q22/HIGHZ_SGC_Q22_500"
output_base: "output/Q22/HIGHZ_SGC_Q22_1000_1"

# Model parameters
v_th: 420
delta_v: 30
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [253.91, 249.59]
  - [249.59, 271.51]
