# MCMC simulation settings
file_base: "data/Q0023"
snapnum: 2
#output_base: "output/Q23/LOWZ_NGC_Q23_500"
output_base: "output/Q23/LOWZ_NGC_Q23_1000_1"

# Model parameters
v_th: 595.6
delta_v: 130.3
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [26.677, 70.708]
  - [70.708, 189.910]
