# MCMC simulation settings
file_base: "data/Q0023"
snapnum: 0
#output_base: "output/Q23/HIGHZ_SGC_Q23_500"
output_base: "output/Q23/HIGHZ_SGC_Q23_1000_1"

# Model parameters
v_th: 397.3
delta_v: 53.1
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [787.75, 1684.02]
  - [1684.02, 3648.14]
