# MCMC simulation settings
file_base: "data/Q0023"
snapnum: 2
#output_base: "output/Q23/LOWZ_SGC_Q23_500"
output_base: "output/Q23/LOWZ_SGC_Q23_1000"

# Model parameters
v_th: 592.3
delta_v: 131.8
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [58.19, 136.25]
  - [136.25, 321.82]
