# MCMC simulation settings
file_base: "data/Q0024"
snapnum: 0
#output_base: "output/Q24/HIGHZ_SGC_Q24_500"
output_base: "output/Q24/HIGHZ_SGC_Q24_1000_1"

# Model parameters
v_th: 446.2
delta_v: 64.3
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [506.57, 813.39]
  - [813.39, 1334.86]
