# MCMC simulation settings
file_base: "data/Q0024"
snapnum: 2
#output_base: "output/Q24/LOWZ_SGC_Q24_500"
output_base: "output/Q24/LOWZ_SGC_Q24_1000"

# Model parameters
v_th: 529.6
delta_v: 101.8
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [119.16, 265.52]
  - [265.52, 594.68]
