# MCMC simulation settings
file_base: "data/Q0024"
snapnum: 0
#output_base: "output/Q24/HIGHZ_NGC_Q24_500"
output_base: "output/Q24/HIGHZ_NGC_Q24_1000_2"

# Model parameters
v_th: 503.2
delta_v: 101.5
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [138.24, 302.13]
#  - [302.13, 664.67]

#step_covariance:
#  - [137.49, 305.28]
#  - [305.28, 680.58]

step_covariance:
  - [119.16, 265.52]
  - [265.52, 594.68]
