# MCMC simulation settings
file_base: "data/Q0025"
snapnum: 2
#output_base: "output/Q25/LOWZ_NGC_Q25_500"
output_base: "output/Q25/LOWZ_NGC_Q25_1000_1"

# Model parameters
v_th: 580.3
delta_v: 128.6
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [166.226, 406.583]
  - [406.583, 997.843]
