# MCMC simulation settings
file_base: "data/Q0025"
snapnum: 0
#output_base: "output/Q25/HIGHZ_NGC_Q25_500"
output_base: "output/Q25/HIGHZ_NGC_Q25_1000_2"

# Model parameters
v_th: 544.4
delta_v: 122.5
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [247.75, 582.18]
#  - [582.18, 1373.59]

#step_covariance:
#  - [345.94, 789.62]
#  - [789.62, 1812.8]

step_covariance:
  - [398.85, 939.55]
  - [939.55, 2223.5]
