# MCMC simulation settings
file_base: "data/Q0025"
snapnum: 0
#output_base: "output/Q25/HIGHZ_SGC_Q25_500"
output_base: "output/Q25/HIGHZ_SGC_Q25_1000_1"

# Model parameters
v_th: 418.3
delta_v: 60
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [294.71, 560.08]
  - [560.08, 1085.51]
