# MCMC simulation settings
file_base: "data/Q0025"
snapnum: 2
#output_base: "output/Q25/LOWZ_SGC_Q25_500"
output_base: "output/Q25/LOWZ_SGC_Q25_1000"

# Model parameters
v_th: 586.1
delta_v: 134
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [398.85, 939.55]
  - [939.55, 2223.5]
