# MCMC simulation settings
file_base: "data/Q0026"
snapnum: 2
#output_base: "output/Q26/LOWZ_NGC_Q26_500"
output_base: "output/Q26/LOWZ_NGC_Q26_1000_1"

# Model parameters
v_th: 515
delta_v: 105.7
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [11.631, 23.392]
  - [23.392, 48.126]
