# MCMC simulation settings
file_base: "data/Q0026"
snapnum: 0
#output_base: "output/Q26/HIGHZ_NGC_Q26_500"
output_base: "output/Q26/HIGHZ_NGC_Q26_1000_1"

# Model parameters
v_th: 443.6
delta_v: 78.2
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [73.35, 151.11]
#  - [151.11, 314.13]

step_covariance:
  - [100.39, 190.29]
  - [190.29, 364.77]
