# MCMC simulation settings
file_base: "data/Q0026"
snapnum: 2
#output_base: "output/Q26/LOWZ_SGC_Q26_500"
output_base: "output/Q26/LOWZ_SGC_Q26_1000"

# Model parameters
v_th: 509.9
delta_v: 107
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [100.39, 190.29]
  - [190.29, 364.77]
