# MCMC simulation settings
file_base: "data/Q0026"
snapnum: 0
#output_base: "output/Q26/HIGHZ_SGC_Q26_500"
output_base: "output/Q26/HIGHZ_SGC_Q26_1000_1"

# Model parameters
v_th: 410.6
delta_v: 52.3
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [937.48, 1492.17]
  - [1492.17, 2446.65]
