# MCMC simulation settings
file_base: "data/Q0027"
snapnum: 0
#output_base: "output/Q27/HIGHZ_SGC_Q27_500"
output_base: "output/Q27/HIGHZ_SGC_Q27_1000_1"

# Model parameters
v_th: 417.7
delta_v: 54.4
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [500.73, 769.64]
  - [769.64, 1213.29]
