# MCMC simulation settings
file_base: "data/Q0027"
snapnum: 2
#output_base: "output/Q27/LOWZ_SGC_Q27_500"
output_base: "output/Q27/LOWZ_SGC_Q27_1000"

# Model parameters
v_th: 543
delta_v: 114.9
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [34.31, 64.84]
  - [64.84, 124.68]
