# MCMC simulation settings
file_base: "data/Q0028"
snapnum: 2
#output_base: "output/Q28/LOWZ_NGC_Q28_500"
output_base: "output/Q28/LOWZ_NGC_Q28_1000_1"

# Model parameters
v_th: 481.5
delta_v: 77
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [34.532, 53.614]
  - [53.614, 85.376]
