# MCMC simulation settings
file_base: "data/Q0028"
snapnum: 0
#output_base: "output/Q28/HIGHZ_SGC_Q28_500"
output_base: "output/Q28/HIGHZ_SGC_Q28_1000_1"

# Model parameters
v_th: 380.4
delta_v: 20.4
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [804.62, 1088.79]
  - [1088.79, 1550.22]
