# MCMC simulation settings
file_base: "data/Q0029"
snapnum: 0
#output_base: "output/Q29/HIGHZ_SGC_Q29_500"
output_base: "output/Q29/HIGHZ_SGC_Q29_1000_1"

# Model parameters
v_th: 423
delta_v: 56.4
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [75.65, 80.94]
  - [80.94, 102.74]
