# MCMC simulation settings
file_base: "data/Q0029"
snapnum: 0
#output_base: "output/Q29/HIGHZ_NGC_Q29_500"
output_base: "output/Q29/HIGHZ_NGC_Q29_1000_1"

# Model parameters
v_th: 549.2
delta_v: 124.2
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [24.48, 57.80]
#  - [57.80, 137.88]

step_covariance:
  - [15.65, 37.21]
  - [37.21, 90.19]
