# MCMC simulation settings
file_base: "data/Q0029"
snapnum: 2
#output_base: "output/Q29/LOWZ_SGC_Q29_500"
output_base: "output/Q29/LOWZ_SGC_Q29_1000"

# Model parameters
v_th: 568.1
delta_v: 128.5
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [15.65, 37.21]
  - [37.21, 90.19]
