# MCMC simulation settings
file_base: "data/Q0029"
snapnum: 2
#output_base: "output/Q29/LOWZ_NGC_Q29_500"
output_base: "output/Q29/LOWZ_NGC_Q29_1000_1"

# Model parameters
v_th: 531.9
delta_v: 109.8
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [60.258, 147.701]
  - [147.701, 364.969]
