# MCMC simulation settings
file_base: "data/Q0002"
snapnum: 0
#output_base: "output/Q2/HIGHZ_SGC_Q2_500"
output_base: "output/Q2/HIGHZ_SGC_Q2_1000_2"

# Model parameters
v_th: 407.1
delta_v: 6.9
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [1203.29, 751.15]
  - [751.15, 546.52]
