# MCMC simulation settings
file_base: "data/Q0002"
snapnum: 2
#output_base: "output/Q2/LOWZ_NGC_Q2_500"
output_base: "output/Q2/LOWZ_NGC_Q2_1000_3"

# Model parameters
v_th: 585
delta_v: 132
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [8.99, 17.34]
  - [17.34, 38.87]
