# MCMC simulation settings
file_base: "data/Q0003"
snapnum: 0
output_base: "output/Q3/HIGHZ_SGC_Q3_1000_1"

# Model parameters
v_th: 456.9
delta_v: 88.9
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [602.49, 931.18]
  - [931.18, 1475.86]
