# MCMC simulation settings
file_base: "data/Q0003"
snapnum: 2
output_base: "output/Q3/LOWZ_NGC_Q3_1000_2"

# Model parameters
v_th: 575.4
delta_v: 131.1
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [10.150, 28.223]
  - [28.223, 81.341]
