# MCMC simulation settings
file_base: "data/Q0004"
snapnum: 0
#output_base: "output/Q4/HIGHZ_SGC_Q4_500"
output_base: "output/Q4/HIGHZ_SGC_Q4_1000_1"

# Model parameters
v_th: 496.5
delta_v: 97.2
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [1052.90, 1579.80]
  - [1579.80, 2457.24]
