# MCMC simulation settings
file_base: "data/Q0004"
snapnum: 2
#output_base: "output/Q4/LOWZ_NGC_Q4_500"
output_base: "output/Q4/LOWZ_NGC_Q4_1000_2"

# Model parameters
v_th: 675
delta_v: 160
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [255.98, 641.52]
  - [641.52, 1615.96]
