# MCMC simulation settings
file_base: "data/Q0005"
snapnum: 0
#output_base: "output/Q5/HIGHZ_NGC_Q5_500"
output_base: "output/Q5/HIGHZ_NGC_Q5_1000_3"

# Model parameters
#v_th: 467.4
#delta_v: 89.4
v_th: 459
delta_v: 69.3
ns_type: 0

#n_mc: 500
n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

step_covariance:
  - [92.387, 155.429]
  - [155.429, 269.838]
