# MCMC simulation settings
file_base: "data/Q0005"
snapnum: 0
#output_base: "output/Q5/HIGHZ_SGC_Q5_500"
output_base: "output/Q5/HIGHZ_SGC_Q5_1000_1"

# Model parameters
v_th: 416.8
delta_v: 30.8
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [303.29, 353.25]
  - [353.25, 434.89]
