# MCMC simulation settings
file_base: "data/Q0005"
snapnum: 2
#output_base: "output/Q5/LOWZ_NGC_Q5_500"
output_base: "output/Q5/LOWZ_NGC_Q5_1000_4"

# Model parameters
v_th: 525
delta_v: 100
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [68.00, 99.68]
  - [99.68, 153.83]
