# MCMC simulation settings
file_base: "data/Q0005"
snapnum: 2
#output_base: "output/Q5/LOWZ_SGC_Q5_500"
output_base: "output/Q5/LOWZ_SGC_Q5_1000"

# Model parameters
v_th: 481.8
delta_v: 70.8
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [92.387, 155.429]
  - [155.429, 269.838]
