# MCMC simulation settings
file_base: "data/Q0006"
snapnum: 0
#output_base: "output/Q6/HIGHZ_NGC_Q6_500"
output_base: "output/Q6/HIGHZ_NGC_Q6_1000_3"

# Model parameters
#v_th: 467.4
#delta_v: 89.4
v_th: 605.25
delta_v: 148.88
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

step_covariance:
  - [9.62, 25.36]
  - [25.36, 68.37]
