# MCMC simulation settings
file_base: "data/Q0006"
snapnum: 0
#output_base: "output/Q6/HIGHZ_SGC_Q6_500"
output_base: "output/Q6/HIGHZ_SGC_Q6_1000_1"

# Model parameters
v_th: 464.8
delta_v: 91.8
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [307.63, 459.87]
  - [459.87, 705.50]
