# MCMC simulation settings
file_base: "data/Q0006"
snapnum: 2
#output_base: "output/Q6/LOWZ_NGC_Q6_500"
output_base: "output/Q6/LOWZ_NGC_Q6_1000_2"

# Model parameters
v_th: 600.6
delta_v: 138.9
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [54.85, 155.62]
  - [155.62, 445.16]
