# MCMC simulation settings
file_base: "data/Q0007"
snapnum: 0
#output_base: "output/Q7/HIGHZ_SGC_Q7_500"
output_base: "output/Q7/HIGHZ_SGC_Q7_1000_1"

# Model parameters
v_th: 420
delta_v: 52
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [293.05, 459.56]
  - [459.56, 742.17]

