# MCMC simulation settings
file_base: "data/Q0007"
snapnum: 0
#output_base: "output/Q7/HIGHZ_NGC_Q7_500"
output_base: "output/Q7/HIGHZ_NGC_Q7_1000_3"

# Model parameters
#v_th: 467.4
#delta_v: 89.4
v_th: 505.5
delta_v: 105.2
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

step_covariance:
  - [49.94, 108.23]
  - [108.23, 237.17]

