# MCMC simulation settings
file_base: "data/Q0007"
snapnum: 2
#output_base: "output/Q7/LOWZ_SGC_Q7_500"
output_base: "output/Q7/LOWZ_SGC_Q7_1000"

# Model parameters
v_th: 595.8
delta_v: 132.3
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [49.94, 108.23]
  - [108.23, 237.17]

