# MCMC simulation settings
file_base: "data/Q0007"
snapnum: 2
#output_base: "output/Q7/LOWZ_NGC_Q7_500"
output_base: "output/Q7/LOWZ_NGC_Q7_1000_1"

# Model parameters
v_th: 587.9
delta_v: 128.1
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [10.543, 25.113]
  - [25.113, 62.971]

