# MCMC simulation settings
file_base: "data/Q0008"
snapnum: 0
#output_base: "output/Q8/HIGHZ_NGC_Q8_500"
output_base: "output/Q8/HIGHZ_NGC_Q8_1000_3"

# Model parameters
#v_th: 467.4
#delta_v: 89.4
v_th: 450.0
delta_v: 80.0
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [85.71, 157.87]
#  - [157.87, 293.45]

step_covariance:
  - [61.24, 106.48]
  - [106.48, 188.31]
