# MCMC simulation settings
file_base: "data/Q0008"
snapnum: 0
#output_base: "output/Q8/HIGHZ_SGC_Q8_500"
output_base: "output/Q8/HIGHZ_SGC_Q8_1000_1"

# Model parameters
v_th: 389.5
delta_v: 30.6
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [712.09, 898.98]
  - [898.98, 1170.42]
