# MCMC simulation settings
file_base: "data/Q0008"
snapnum: 2
#output_base: "output/Q8/LOWZ_SGC_Q8_500"
output_base: "output/Q8/LOWZ_SGC_Q8_1000"

# Model parameters
v_th: 545.2
delta_v: 122.9
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [61.24, 106.48]
  - [106.48, 188.31]
