# MCMC simulation settings
file_base: "data/Q0008"
snapnum: 2
#output_base: "output/Q8/LOWZ_NGC_Q8_500"
output_base: "output/Q8/LOWZ_NGC_Q8_1000_2"

# Model parameters
v_th: 539.5
delta_v: 116.82
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [304.02, 687.93]
  - [687.93, 1560.32]
