# MCMC simulation settings
file_base: "data/Q0009"
snapnum: 0
#output_base: "output/Q9/HIGHZ_NGC_Q9_500"
output_base: "output/Q9/HIGHZ_NGC_Q9_1000_3"

# Model parameters
#v_th: 467.4
#delta_v: 89.4
v_th: 496.1
delta_v: 102.2
ns_type: 0

n_mc: 1000
kmax: 0.4

#step_covariance:
#  - [125.82, 268.14]
#  - [268.14, 576.97]

#step_covariance:
#  - [69.0284, 143.9178]
#  - [143.9178, 303.2923]

#step_covariance:
#  - [140.00, 301.75]
#  - [301.75, 656.36]
step_covariance:
  - [104.22, 222.79]
  - [222.79, 480.85]
