# MCMC simulation settings
file_base: "data/Q0009"
snapnum: 2
#output_base: "output/Q9/LOWZ_NGC_Q9_500"
output_base: "output/Q9/LOWZ_NGC_Q9_1000_1"

# Model parameters
v_th: 548.5
delta_v: 118.6
ns_type: 0

n_mc: 1000
kmax: 0.4

step_covariance:
  - [68.625, 143.414]
  - [143.414, 302.720]
