# MCMC simulation settings
file_base: "data/Q0009"
snapnum: 2
#output_base: "output/Q9/LOWZ_SGC_Q9_500"
output_base: "output/Q9/LOWZ_SGC_Q9_1000"

# Model parameters
v_th: 527.6
delta_v: 110.4
ns_type: 1

n_mc: 1000
kmax: 0.4

step_covariance:
  - [104.22, 222.79]
  - [222.79, 480.85]
